In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
# NaN값은 결측치

In [4]:
data.dropna() # na값이 하나라도 있으면 제거

0    1    2
0  1.0  6.5  3.0

In [6]:
data.dropna(how='any') # 기본값이 any로 설정되어 있음
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [7]:
data[3] = np.nan

In [8]:
data

0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [9]:
data[5] = 3
data

0    1    2   3  5
0  1.0  6.5  3.0 NaN  3
1  1.0  NaN  NaN NaN  3
2  NaN  NaN  NaN NaN  3
3  NaN  6.5  3.0 NaN  3

In [15]:
data.dropna()
data.dropna(axis=0)
data.dropna(how='all')
data.dropna(how='all', axis=1)

0    1    2  5
0  1.0  6.5  3.0  3
1  1.0  NaN  NaN  3
2  NaN  NaN  NaN  3
3  NaN  6.5  3.0  3

In [16]:
df = pd.DataFrame(np.random.standard_normal((10,4)))
df

0         1         2         3
0 -0.277262  0.072895  0.517666  0.256663
1  1.280681  0.527949  0.782815  0.172467
2 -0.887238  1.225264 -0.092928  0.486136
3  1.523598  0.727649 -0.058010  1.609596
4  1.505088 -1.466758  0.393256  0.846752
5 -1.277175 -0.032628  0.879352 -0.285832
6 -0.467464  0.754637  0.060542  1.057485
7 -0.469501  0.880271  0.268511 -0.749769
8  0.896593  0.740793 -1.589223 -0.286275
9 -2.316476  0.062987  0.141297 -1.953214

In [17]:
df.iloc[:,1]

0    0.072895
1    0.527949
2    1.225264
3    0.727649
4   -1.466758
5   -0.032628
6    0.754637
7    0.880271
8    0.740793
9    0.062987
Name: 1, dtype: float64

In [18]:
df.iloc[:5,2] = np.nan
df

0         1         2         3
0 -0.277262  0.072895       NaN  0.256663
1  1.280681  0.527949       NaN  0.172467
2 -0.887238  1.225264       NaN  0.486136
3  1.523598  0.727649       NaN  1.609596
4  1.505088 -1.466758       NaN  0.846752
5 -1.277175 -0.032628  0.879352 -0.285832
6 -0.467464  0.754637  0.060542  1.057485
7 -0.469501  0.880271  0.268511 -0.749769
8  0.896593  0.740793 -1.589223 -0.286275
9 -2.316476  0.062987  0.141297 -1.953214

In [19]:
# 3열의 5,7번 행 데이터를 NaN으로 만들기
df.iloc[5:8:2,3] = np.nan
df

0         1         2         3
0 -0.277262  0.072895       NaN  0.256663
1  1.280681  0.527949       NaN  0.172467
2 -0.887238  1.225264       NaN  0.486136
3  1.523598  0.727649       NaN  1.609596
4  1.505088 -1.466758       NaN  0.846752
5 -1.277175 -0.032628  0.879352       NaN
6 -0.467464  0.754637  0.060542  1.057485
7 -0.469501  0.880271  0.268511       NaN
8  0.896593  0.740793 -1.589223 -0.286275
9 -2.316476  0.062987  0.141297 -1.953214

In [30]:
df.iloc[3,3] = np.nan


In [32]:
df

0         1         2         3
0 -0.277262  0.072895       NaN  0.256663
1  1.280681  0.527949       NaN  0.172467
2 -0.887238  1.225264       NaN  0.486136
3  1.523598  0.727649       NaN       NaN
4  1.505088 -1.466758       NaN       NaN
5 -1.277175 -0.032628  0.879352       NaN
6 -0.467464  0.754637  0.060542  1.057485
7 -0.469501  0.880271  0.268511       NaN
8  0.896593  0.740793 -1.589223 -0.286275
9 -2.316476  0.062987  0.141297 -1.953214

In [47]:
df.dropna(thresh=3) # 하나의 행에 몇개의 데이터가 있는지

0         1         2         3
0 -0.277262  0.072895       NaN  0.256663
1  1.280681  0.527949       NaN  0.172467
2 -0.887238  1.225264       NaN  0.486136
5 -1.277175 -0.032628  0.879352       NaN
6 -0.467464  0.754637  0.060542  1.057485
7 -0.469501  0.880271  0.268511       NaN
8  0.896593  0.740793 -1.589223 -0.286275
9 -2.316476  0.062987  0.141297 -1.953214

In [48]:
df

0         1         2         3
0 -0.277262  0.072895       NaN  0.256663
1  1.280681  0.527949       NaN  0.172467
2 -0.887238  1.225264       NaN  0.486136
3  1.523598  0.727649       NaN       NaN
4  1.505088 -1.466758       NaN       NaN
5 -1.277175 -0.032628  0.879352       NaN
6 -0.467464  0.754637  0.060542  1.057485
7 -0.469501  0.880271  0.268511       NaN
8  0.896593  0.740793 -1.589223 -0.286275
9 -2.316476  0.062987  0.141297 -1.953214

In [50]:
df.fillna(0) # 0으로 채우기

0         1         2         3
0 -0.277262  0.072895  0.000000  0.256663
1  1.280681  0.527949  0.000000  0.172467
2 -0.887238  1.225264  0.000000  0.486136
3  1.523598  0.727649  0.000000  0.000000
4  1.505088 -1.466758  0.000000  0.000000
5 -1.277175 -0.032628  0.879352  0.000000
6 -0.467464  0.754637  0.060542  1.057485
7 -0.469501  0.880271  0.268511  0.000000
8  0.896593  0.740793 -1.589223 -0.286275
9 -2.316476  0.062987  0.141297 -1.953214

In [51]:
df.fillna({2:1, 3:10})

0         1         2          3
0 -0.277262  0.072895  1.000000   0.256663
1  1.280681  0.527949  1.000000   0.172467
2 -0.887238  1.225264  1.000000   0.486136
3  1.523598  0.727649  1.000000  10.000000
4  1.505088 -1.466758  1.000000  10.000000
5 -1.277175 -0.032628  0.879352  10.000000
6 -0.467464  0.754637  0.060542   1.057485
7 -0.469501  0.880271  0.268511  10.000000
8  0.896593  0.740793 -1.589223  -0.286275
9 -2.316476  0.062987  0.141297  -1.953214

In [52]:
df = pd.DataFrame(np.random.standard_normal((10,4)))
df

0         1         2         3
0 -0.250362 -0.822616  1.143118 -1.432832
1 -0.081564  1.423066 -1.427387  0.645091
2  0.174175 -0.676818  2.037254  0.845254
3 -0.815219 -0.161759 -0.594208 -1.142552
4  0.330520  0.417213 -2.209118  0.233761
5  1.330951 -2.212194  0.123337 -1.018437
6  0.435466  0.208377  1.138740  0.189208
7 -0.964156  0.691156  1.166710  0.517773
8 -0.342026 -1.048002  0.758114  1.115088
9  0.347172 -0.490378  0.716292  0.227392

In [53]:
df.iloc[4:, 1] = np.nan
df.iloc[7:, 3] = np.nan
df

0         1         2         3
0 -0.250362 -0.822616  1.143118 -1.432832
1 -0.081564  1.423066 -1.427387  0.645091
2  0.174175 -0.676818  2.037254  0.845254
3 -0.815219 -0.161759 -0.594208 -1.142552
4  0.330520       NaN -2.209118  0.233761
5  1.330951       NaN  0.123337 -1.018437
6  0.435466       NaN  1.138740  0.189208
7 -0.964156       NaN  1.166710       NaN
8 -0.342026       NaN  0.758114       NaN
9  0.347172       NaN  0.716292       NaN

In [54]:
df.fillna(method='ffill')

0         1         2         3
0 -0.250362 -0.822616  1.143118 -1.432832
1 -0.081564  1.423066 -1.427387  0.645091
2  0.174175 -0.676818  2.037254  0.845254
3 -0.815219 -0.161759 -0.594208 -1.142552
4  0.330520 -0.161759 -2.209118  0.233761
5  1.330951 -0.161759  0.123337 -1.018437
6  0.435466 -0.161759  1.138740  0.189208
7 -0.964156 -0.161759  1.166710  0.189208
8 -0.342026 -0.161759  0.758114  0.189208
9  0.347172 -0.161759  0.716292  0.189208

In [55]:
df.fillna(method='ffill', limit=2) # 채우는 데이터 수에 제한을 걸 수 있음

0         1         2         3
0 -0.250362 -0.822616  1.143118 -1.432832
1 -0.081564  1.423066 -1.427387  0.645091
2  0.174175 -0.676818  2.037254  0.845254
3 -0.815219 -0.161759 -0.594208 -1.142552
4  0.330520 -0.161759 -2.209118  0.233761
5  1.330951 -0.161759  0.123337 -1.018437
6  0.435466       NaN  1.138740  0.189208
7 -0.964156       NaN  1.166710  0.189208
8 -0.342026       NaN  0.758114  0.189208
9  0.347172       NaN  0.716292       NaN

In [56]:
data = pd.Series([1, np.nan, 3.5, np.nan, 90])
data

0     1.0
1     NaN
2     3.5
3     NaN
4    90.0
dtype: float64

In [59]:
data.fillna(data.median())

0     1.0
1     3.5
2     3.5
3     3.5
4    90.0
dtype: float64

In [62]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two", "two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4
7  two   4

In [63]:
data.duplicated() # 중복된 데이터 탐색(첫번째 발견은 중복이 아님)

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
dtype: bool

In [64]:
data.drop_duplicates() # 중복데이터 제거

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [65]:
data['k3'] = range(8)
data

k1  k2  k3
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6
7  two   4   7

In [66]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [69]:
# 행이 아닌 열을 기준으로 비교하고 삭제하고 싶을 때
data.drop_duplicates(subset=['k1'])
data.drop_duplicates(['k1']) # 동일한 결과를 출력

k1  k2  k3
0  one   1   0
1  two   1   1

In [70]:
data.drop_duplicates(subset=['k1','k2']) # 여러개의 열을 기준으로 중복 제거

k1  k2  k3
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

In [71]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [72]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [73]:
# food값에 해당하는 데이터를 새로운 열에 추가
data['animal'] = data['food'].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [76]:
def get_animal(x):
    return meat_to_animal[x]
data['animal'] = data['food'].map(get_animal)
data # 위의 셀과 동일한 결과

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [77]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [81]:
data.replace(-999, np.nan)
data.replace([-999, -1000], np.nan)
data.replace([-999, -1000], [np.nan, 0])
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [82]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [83]:
data.index

Index(['Ohio', 'Colorado', 'New York'], dtype='object')

In [84]:
def trans(x):
    return x[:4].upper() # 대문자로 변환
data.index = data.index.map(trans)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [ ]:
# 연속형, 범주형
# 나이같은 경우: 연속형
# class로 나눠지는 데이터는 범주형

# 연속형 변수: 연속적인 값(나이, 점수, 몸무게, 가격, ...)
# 범주형 변수: 이산적인 값(서로 다른 것으로 구분되는가 = 성별, 혈액형, 학점(A, B+, ..),...)
# 연속형 변수를 범주형 변수로 만들 수 있음(연령 24세 -> 20대)

In [90]:
ages = [12,13,20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 37, 60, 100]

In [91]:
age_category = pd.cut(ages, bins)
age_category

[NaN, NaN, (18.0, 25.0], (18.0, 25.0], (18.0, 25.0], ..., (25, 37], (60, 100], (37, 60], (37, 60], (25, 37]]
Length: 14
Categories (4, interval[int64, right]): [(18, 25] < (25, 37] < (37, 60] < (60, 100]]

In [ ]:
range(5,10) => 5,6,7,8,9(10은 미포함) => [5, 10)

In [92]:
age_category.codes

array([-1, -1,  0,  0,  0,  1,  0,  0,  1,  1,  3,  2,  2,  1], dtype=int8)

In [93]:
age_category.categories

IntervalIndex([(18, 25], (25, 37], (37, 60], (60, 100]], dtype='interval[int64, right]')

In [94]:
pd.cut(ages, bins, right=False) # 왼쪽을 포함하게 됨(range와 범위표현이 같아짐)

[NaN, NaN, [18.0, 25.0), [18.0, 25.0), [25.0, 37.0), ..., [25, 37), [60, 100), [37, 60), [37, 60), [25, 37)]
Length: 14
Categories (4, interval[int64, left]): [[18, 25) < [25, 37) < [37, 60) < [60, 100)]

In [95]:
group_names = ['one','two','three','four']
pd.cut(ages, bins, labels=group_names)

[NaN, NaN, 'one', 'one', 'one', ..., 'two', 'four', 'three', 'three', 'two']
Length: 14
Categories (4, object): ['one' < 'two' < 'three' < 'four']

In [96]:
pd.describe_option()
# pd.set_option('display.max_columns', 10)

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.column_space No description available.
    [defa

In [97]:
data = np.random.uniform(size=20)
data

array([0.20812249, 0.05402696, 0.46855406, 0.21963825, 0.31709151,
       0.10060223, 0.00815129, 0.33174489, 0.51521371, 0.06092207,
       0.7474271 , 0.96692259, 0.46719568, 0.58184772, 0.34928191,
       0.14624622, 0.1973821 , 0.05939054, 0.83091424, 0.70359008])

In [98]:
data_cut = pd.cut(data, 4) # 동일한 4개의 범위를 분리
data_cut

[(0.00719, 0.248], (0.00719, 0.248], (0.248, 0.488], (0.00719, 0.248], (0.248, 0.488], ..., (0.00719, 0.248], (0.00719, 0.248], (0.00719, 0.248], (0.727, 0.967], (0.488, 0.727]]
Length: 20
Categories (4, interval[float64, right]): [(0.00719, 0.248] < (0.248, 0.488] < (0.488, 0.727] < (0.727, 0.967]]

In [99]:
data_cut.codes

array([0, 0, 1, 0, 1, 0, 0, 1, 2, 0, 3, 3, 1, 2, 1, 0, 0, 0, 3, 2],
      dtype=int8)

In [100]:
pd.value_counts(data_cut.codes) # 구간별 카운트

0    9
1    5
2    3
3    3
dtype: int64

In [101]:
# qcut != cut
data_qcut = pd.qcut(data, 4)
data_qcut

[(0.135, 0.324], (0.007149999999999999, 0.135], (0.324, 0.532], (0.135, 0.324], (0.135, 0.324], ..., (0.135, 0.324], (0.135, 0.324], (0.007149999999999999, 0.135], (0.532, 0.967], (0.532, 0.967]]
Length: 20
Categories (4, interval[float64, right]): [(0.007149999999999999, 0.135] < (0.135, 0.324] < (0.324, 0.532] < (0.532, 0.967]]

In [102]:
pd.value_counts(data_qcut) # 구간별 동일하게 데이터 개수 분리됨

(0.007149999999999999, 0.135]    5
(0.135, 0.324]                   5
(0.324, 0.532]                   5
(0.532, 0.967]                   5
dtype: int64

In [104]:
group_names = ['one','two','three','four']
data_cateq = pd.qcut(data, 4, labels=group_names)
data_cateq

['two', 'one', 'three', 'two', 'two', ..., 'two', 'two', 'one', 'four', 'four']
Length: 20
Categories (4, object): ['one' < 'two' < 'three' < 'four']

In [105]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)), columns=['a','b','c','d'])
data.describe() # 기술통계

a            b            c            d
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.043202     0.024151    -0.036534    -0.008814
std       0.972657     0.988952     1.033641     1.001346
min      -2.951746    -3.037975    -3.296759    -2.868684
25%      -0.597532    -0.619365    -0.778825    -0.699771
50%       0.038786     0.000568    -0.050312    -0.009114
75%       0.712352     0.649789     0.688985     0.733728
max       3.530097     3.077798     2.712648     3.227116

In [106]:
data[data['b'].abs() > 3]

a         b         c         d
426 -0.520956 -3.037975  0.597633 -0.038065
670  0.217045  3.077798  0.926285  0.311245

In [107]:
sampler = np.random.permutation(5)
sampler

array([4, 3, 0, 1, 2])

In [108]:
df = pd.DataFrame(np.arange(5*7).reshape(5,7))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [109]:
df.iloc[sampler]

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20

In [112]:
df.take(sampler) # iloc과 유사한 기능을 가짐. 다른점은 행 또는 열 단위로 추출할 때 빠름
df.take(sampler, axis=1) # sampler에 있는 열만 출력

4   3   0   1   2
0   4   3   0   1   2
1  11  10   7   8   9
2  18  17  14  15  16
3  25  24  21  22  23
4  32  31  28  29  30

In [115]:
df.sample(2) # 랜덤한 행을 추출

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [117]:
choice = pd.Series([5,7,-3,6,2])
choice.sample(4) # 랜덤으로 지정한 데이터 개수를 추출

0    5
3    6
2   -3
4    2
dtype: int64

In [119]:
choice.sample(10, replace=True) # 중복출력 가능

2   -3
3    6
0    5
1    7
3    6
1    7
1    7
4    2
2   -3
1    7
dtype: int64

In [ ]:
# 이번주 로또번호 5셋 출력하기(행당 6개의 숫자)

In [156]:
nums = pd.Series(np.arange(1,46))
pd.DataFrame([nums.sample(6).to_numpy() for i in range(5)])

0   1   2   3   4   5
0   6  21  12  44  43  33
1  44  37   5  30  12  33
2  18  36  45  20  22  24
3  28  16  38   6  11  18
4  22  37  36  39  13  32

In [157]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# 원핫인코딩: 범주형 문자 데이터 -> 수치로 변환

In [158]:
pd.get_dummies(df['key']) # 원핫인코딩

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [160]:
df.key

0    b
1    b
2    a
3    c
4    a
5    b
Name: key, dtype: object

In [161]:
df['key']

0    b
1    b
2    a
3    c
4    a
5    b
Name: key, dtype: object

In [159]:
dummies = pd.get_dummies(df.key, dtype='int', prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [164]:
df.data1
df[['data1']].join(dummies)

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [ ]:
i have a hotdog
i, have, a, hotdog
1  0     0   0
0   1    0   0
0   0    1    0
0   0   0    1

In [ ]:
코미디, 액션, 호러, 모험,...
-> 열로 변환
액션 호러
모험, 판타지 => unique를 파악 -> get_dummies = 원핫인코딩