In [1]:
import numpy as np

In [5]:
# 자릿수 지정
np.array([1.23456789]) # 일반적으로  8자리까지 나옴


array([1.23456789])

In [7]:
np.set_printoptions(precision=4)

In [9]:
np.array([1.23456789])  # 맨 뒤의 숫자는 반올림 함

array([1.2346])

In [19]:
# 출력 갯수 조절
np.set_printoptions(threshold=100)
np.set_printoptions(threshold=np.inf)   # 출력 한계를 없에겠다.
# 턱걸이처럼 숫자를 세고 넘어가면 중략 처리 (경계선을 의미함)

In [22]:
# np.arange(100)
np.arange(101)

# np.arange(10000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
sentence = '''
안녕하세요
감사해요
잘있어요
다시만나요
'''

In [25]:
sentence

'\n안녕하세요\n감사해요\n잘있어요\n다시만나요\n'

In [27]:
sentence.count('/n')

0

In [29]:
print('\\')

\


In [32]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
arr @ arr.T
# 2번째 열의 갯수와 첫번쨰 행의 갯수로 

array([[ 55, 130],
       [130, 330]])

In [35]:
np.sqrt(arr)    # 제곱근 구하기

array([[1.    , 1.4142, 1.7321, 2.    , 2.2361],
       [2.4495, 2.6458, 2.8284, 3.    , 3.1623]])

In [39]:
xarr = np.arange(1,6)
yarr = np.arange(11,16)
cond = np.array([True, False, True, True, False])

In [42]:
xarr[cond], yarr[~cond] # ~는 not

(array([1, 3, 4]), array([12, 15]))

In [43]:
np.where(cond, xarr, yarr)  # cond에 충족하면 xarr 아니면 yarr 소환
# 트루면 출력 (파이썬의 삼항연산자와 같음)

array([ 1, 12,  3,  4, 15])

In [46]:
arr = np.array([1,2,3,4,5,])
arr

array([1, 2, 3, 4, 5])

In [48]:
arr.cumsum() # 넘어갈수록 더해진 채로 넘어감

array([ 1,  3,  6, 10, 15])

In [50]:
np.save('test',arr)
# 바이너리 형태로 저장됨. 확장자는 npy로 설정됨

In [52]:
np.load('test.npy')

array([1, 2, 3, 4, 5])

In [54]:
np.savez('data',a = xarr, b = yarr) # 여러개의 배열을 저장. 확장자는 npz (zip)

In [59]:
x = np.load('data.npz')
x['b']
#딕셔너리라 보면 됨

array([11, 12, 13, 14, 15])