In [2]:
import numpy as np

In [34]:
# 1.
# 넘파이를 사용하여 다음과 같은 행렬을 만든다.
# 10 20 30 40
# 50 60 70 80

np.array([list(range(10,41,10)),list(range(50,81,10))])
np.array(list(range(10,81,10))).reshape(2,-1)
np.arange(10,81,10).reshape(2,-1)
np.linspace(10,80,8, dtype='i4')

array([10, 20, 30, 40, 50, 60, 70, 80])

In [3]:
# 2.
# 다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
# 이 행렬에서 값 7 을 인덱싱한다.
m[1][2]
# 이 행렬에서 값 14 을 인덱싱한다.
m[2][-1]
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[(m == 6) | (m == 7)]
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[(m == 7) | (m == 12)]
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
# ???
m[:2,[3,4]]

array([[3, 4],
       [8, 9]])

In [102]:
# 3. 값이 10에서 49를 원소로 가지고 있는 벡터 만들기
nums = np.array(list(range(10,50))).reshape(5,8)

nums = np.arange(10,50)

nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [103]:
# 4. 3번 배열의 원소를 뒤집어 출력
nums[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [104]:
# 1. 1차원 numpy 배열을 만들어 결과와 같이 출력하기
# [ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]
np.array(list(range(0,29,2)))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [111]:
# 2. 2차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[10, 20, 30, 40],
# 50, 60, 70, 80]]
np.array(list(range(10,81,10))).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [116]:
# 3. 3차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[[ 1, 2, 3],
# [ 4, 5, 6]],

# [[ 7, 8, 9],
# [10, 11, 12]],

# [[13, 14, 15],
# [16, 17, 18]],

# [[19, 20, 21],
# [22, 23, 24]]]

arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])
np.arange(1,25).reshape(2,4,3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [120]:
# 4. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
vector = np.array(range(0, 30, 2))

# 값 24 인덱싱
vector[vector == 24]
#  값 6 인덱싱
vector[vector == 6]

array([6])

In [122]:
# 5. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
matrix = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])

# - 값 8 인덱싱
matrix[matrix==8]
# - 값 2 인덱싱
matrix[matrix==2]
# - 값 9 인덱싱
matrix[matrix==9]
# - 값 15 인덱싱
matrix[matrix==15]

array([15])

In [5]:
# 6. 아래와 같은 행렬을 작성해보세요
# [-1, -2, -3, -4, -5]
np.arange(-5,0)

array([-5, -4, -3, -2, -1])

In [6]:
# 7.
# 다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# 이 배열에서 3의 배수를 찾아라.
x[x % 3 == 0]
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x % 4 == 1]

# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

In [133]:
# 8. 다음 배열을 만들고 슬라이싱, 인덱싱 연습하세요
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

arr2d[1]

array([4, 5, 6])