In [4]:
# 파이썬 => 리스트
def test():
    return 1
lst = [1,2,'3',[1],test(),...]

In [6]:
lst

[1, 2, '3', [1], 1, Ellipsis]

In [2]:
import numpy # numpy는 속도가 빠름, 메모리 할당이 적음, 자료형이 같은 동일한 것만 저장됨
# 벡터 연산을 위해 자주 쓰임
# 행벡터, 열벡터(행렬)
# 행벡터 => x- [x1, x2, x3, ...xn]
# 열벡터 => y =
#[ [y1],
#  [y2],
#  [y3],
#  ...
#  [yn]]

In [3]:
import numpy as np

In [4]:
x = [1,2,3]
arr = np.array(x)

In [5]:
arr

array([1, 2, 3])

In [6]:
type(arr)   # numpy.ndarray

numpy.ndarray

In [6]:
import time

data = list(range(1,10000000))
ans = []

In [2]:
start = time.time()
for i in data :
    ans.append(i*2)
end = time.time()
print(end-start)

0.9418349266052246


In [5]:
arr_data = np.array(data)
arr_data

array([      1,       2,       3, ..., 9999997, 9999998, 9999999])

In [17]:
start = time.time()
ans2 = arr_data * 2 # numpy
end = time.time()
print(end-start)

0.014525651931762695


In [18]:
ans2 # numpy에 

array([       2,        4,        6, ..., 19999994, 19999996, 19999998])

In [20]:
x= [1,2]
y= [3,4]
x + y 

[1, 2, 3, 4]

In [22]:
np.array(x)+np.array(y)

array([4, 6])

In [24]:
# np.array(x) +np.array[[1]] # 내부적으로 길이가 맞아야 계산 가능
np.array(x) + 1 # 1이 x의 배열 전체에 더해짐
#array[1,2] + 1 => [1,1]

array([2, 3])

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

In [26]:
lst = list(range(1,101))

In [29]:
arr = np.array(lst)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [35]:
arr >= 50
arr[(arr >= 50) & (arr<70)]  # boolean 참조 ★★★★★
# true가 되는 값에 대해서 출력

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [39]:
np.array([1,2,3], dtype=np.float32) # dtype(데이터 타입)을 float(소수점)으로 바꾼다. ★★★★★

array([1., 2., 3.], dtype=float32)

In [69]:
# 2차원 배열 만들기
arr = np.array([[1,2,3],[4,5,6]])
arr.ndim # ndim 몇차원인지 알려줌. number dimention
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [56]:
np.array([list(range(1,4)), list(range(4,7))])

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# reshape차원을 바꿀 수 있음/ .shape로 행 렬을 알 수있음
np.array([list(range(1,4)), list(range(4,7))]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
arr[1],[2]
arr[1,2]
arr[::2]

array([[1, 2, 3]])

In [82]:
arr.astype('str')
# dtype='<U11' 나중에 찾아볼 것

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

In [88]:
import numpy as np
kakao = np.loadtxt('kakao_pre.csv',skiprows=1, delimiter=',',dtype=np.float32)
kakao
# skiprows=1 - 첫번째 행 삭제
# delimiter=',' - ,를 기준으로 나눔

array([[  58000.   ,   58900.   ,   57800.   ,   58300.   ,   58237.387,
        1047114.   ],
       [  57200.   ,   57500.   ,   56000.   ,   57200.   ,   57138.57 ,
        2288474.   ],
       [  57500.   ,   58200.   ,   57100.   ,   57700.   ,   57638.03 ,
        1821528.   ],
       ...,
       [  48350.   ,   48850.   ,   48300.   ,   48600.   ,   48600.   ,
        1015126.   ],
       [  48150.   ,   48550.   ,   48050.   ,   48300.   ,   48300.   ,
         889047.   ],
       [  49000.   ,   50300.   ,   49000.   ,   49150.   ,   49150.   ,
        1099015.   ]], dtype=float32)

In [90]:
kakao.shape

(246, 6)

In [37]:
# 값이 5에서 30을 원소로 가지는 2행 벡터 생성
arr2 = np.array(list(range(5,31))).reshape(2,-1) # -1은 관례
arr2

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

In [106]:
arr = np.array (['apple', 'banana', 'peach'])
arr.dtype
# dtype('<U6') u 유니코드 6 내부 요소의 최대 길이값(banana)

dtype('<U6')

In [111]:
# np.array([1,2,3], dtype=np.int64) # 64는 dtype이 붙음
np.array([1,2,3], dtype='i1') # i 뒤에 숫자는 byte
# mac os는 64비트를 기준으로 함

array([1, 2, 3], dtype=int8)

In [11]:
arr1 = np.array(list(range(10,14)))
arr2 = np.array(list(range(10,14)))
arr3 = np.array(list(range(2,4)))
arr1, arr2, arr3

(array([10, 11, 12, 13]), array([10, 11, 12, 13]), array([2, 3]))

In [12]:
arr1 + 10   # 요소간 연산 => 연산할 데이터가 길이가 1일 경우 동일한 크기의 배열로 변환하여 연산을 진행
arr1 * 2    # 행렬 곱셈
# arr1 - arr3 이건 계산을 못함
arr1.reshape(2,2) - arr3 # 해당하는 행과 열에 대해서만 계산을 함
arr1.reshape(2,2) * arr2.reshape(2,2) # 요소간 곱셈

array([[100, 121],
       [144, 169]])

In [15]:
print(arr1, arr2)
np.dot(arr1,arr2) # 행렬 곱셈 

[10 11 12 13] [10 11 12 13]


534

In [131]:
# arr1 != arr2
~(arr1 == arr2) # ~ -> not 연산자

array([False, False, False, False])

In [135]:
# 1~24 까지의 값 2*3*4 행렬
arrr = np.array(list(range(1,25))).reshape(2,3,4)
arrr
np.arange(1,25).reshape(2,3,4)
# np.arange(1,25,2).reshape(2,-1)   

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

# boolean 참조

In [31]:
# boolean 참조
arr = np.arange(1,5)
idx = np.array([True,True,False,False])
arr[idx]


array([1, 2])

In [142]:
np.min(arr)
np.max(arr)

4

In [145]:
arr[(arr == np.min(arr)) | (arr == np.max(arr))]

array([1, 4])

In [151]:
lst = list(range(1,10))
for i in lst:
    if(i == 5):
        print(i)

arr[arr==4]

5


array([4])

In [27]:
# 11부터 20까지의 수가 저장된 배열을 생성
np.arange(11,21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
# 12와 14
arr = np.arange(11,21)
arr[(arr== 12)|(arr== 14)]
# arr[np.array([1, 3])]

array([12, 14])

In [163]:
idx = np.array([0,0,0,1,1,1,1,2,3,4])
arr[idx]

array([11, 11, 11, 12, 12, 12, 12, 13, 14, 15])

In [34]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
arr[:, [3,2,1]]

array([[ 4,  3,  2],
       [ 9,  8,  7],
       [14, 13, 12],
       [19, 18, 17],
       [24, 23, 22]])

In [174]:
# 무한대(inf): np.inf
# np.array([1])/np.array([0])
np.log(0)

C:\Users\wag19\AppData\Local\Temp\ipykernel_1988\2403776038.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [183]:
# np.array()
# np.arange() 
np.zeros(4) 
np.ones((4,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [186]:
# np.linspace(시작할 숫자, 마지막 숫자, 총 데이터 갯수)
np.linspace(0,10,5) # 보간법(interpolate) linear regression랑 비슷함

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
arr2 = arr[:,[1,2,3]]
arr2

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [196]:
# arr2.transpose() # 행과 열을 바꿈
arr2.T.T

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [33]:
# 사과, 딸기, 바나나
data = np.array([[1,5,2],
                [4,3,2],
                [1,2,3]])
price = np.array([[1000],[3000],[5000]])
data.shape
price.shape
# data 배열과 price 배열간 행렬의 곱셈 연산
print(data.dot(price)) # 벡터의 내적
print(data@price)
#cnn할 때 보게 될 코드(이미지 처리)

[[26000]
 [23000]
 [22000]]
[[26000]
 [23000]
 [22000]]


In [223]:
# soft copy
# a = b 데이터 공유가 됨

# deep copy
arr3 = arr.copy()
arr3 = arr3 + 1

arr3, arr

(array([[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]))

In [218]:
a = np.array([1,2,3])
b = a # soft copy

In [219]:
b[1] = 99
b,a

(array([ 1, 99,  3]), array([ 1, 99,  3]))

In [221]:
a = np.array([1,2,3])
b = a.copy()
b[1] = 99
a, b

(array([1, 2, 3]), array([ 1, 99,  3]))

In [234]:
np.random.random() # random도 있음

0.22356123722274157