In [2]:
# 2024.07.06
import numpy as np

In [5]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
# 평탄화 - 하나의 차원으로 합침
arr.ravel()
arr.flatten()   # ★★★★★

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
# np.newaxis - 차원을 한단계 추가
arr[:,np.newaxis]

print(arr[np.newaxis])
arr[np.newaxis].shape
# arr

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


(1, 3, 4)

# 행렬합치기

In [6]:
a1 = np.ones((2,3))
a2 = np.zeros((2,2))
a3 = np.zeros((3,3))
a1,a2,a3

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [5]:
# 수평으로 합치기 (행의 갯수가 같아야 함)
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [27]:
# 수직으로 합치기 (열의 갯수가 같아야 함)
np.vstack([a1,a3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# 행렬 자체의 갯수가 같아야 함
np.dstack([a3, a3]) # depth:깊이    # stack을 더 많이 씀

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [36]:
np.stack([a2, a2]) # dstack보다 많이 씀

a4=  np.arange(1,5).reshape(2,2)
np.stack([a4, a4], axis=1) # axis - 축을 바꿀 수 있음(숫자 바꿔볼 것)

array([[[1, 2],
        [1, 2]],

       [[3, 4],
        [3, 4]]])

In [3]:
a1= np.array([1,2,3])
a2= np.array([11,12,13])

# 위 배열들을 이용해서 array([1,2,3,11,12,13])
np.hstack([a1,a2])

array([ 1,  2,  3, 11, 12, 13])

In [5]:
# 인덱서 함수(실제로는 잘 안 씀)
# np.r_[a1,a2]  # r = row
# np.c_[a1,a2]  # c = coulmn

In [8]:
# tile : 동일한 배열을 연결
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
np.tile(arr, 3)
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [32]:
# tile
arr = [0,0,0,1,1]
np.tile(arr, (3,1))

# stack
np.vstack([arr,arr,arr])

array([[0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1]])

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

In [35]:
x = np.arange(3)
y = np.arange(5)
x,y

(array([0, 1, 2]), array([0, 1, 2, 3, 4]))

In [39]:
a, b = np.meshgrid(x,y)
a, b

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

In [40]:
arr1 = np.arange(3)
arr2 = np.arange(10,13)
np.concatenate([arr1, arr2]) # hstack과 같음

array([ 0,  1,  2, 10, 11, 12])

In [60]:
arr1 = np.arange(6)
arr2 = np.arange(0,51,10)
a,b = np.meshgrid(arr1,arr2)
a+b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [63]:
arr1 = np.arange(6)
arr2 = np.arange(0,51,10)
arr1 + arr2[:,np.newaxis]   # 브로드캐스팅 (잘 안쓰임)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
# 벡터  스칼라
# 1   +   100 = 101
# 2   +       = 102
# 3   +       = 103
# ...
# 위와 같은 계산을 브로드캐스팅


# 행렬(2)   벡터(1)
# 0 1 2     10          10 11 12
# 1 2 3  +  11      =   12 13 14
# 2 3 4     12          14 15 16

In [65]:
# 벡터화 연산
a = np.arange(1,5)
b = np.array([4,2,2,4])
a, b
np.all(a>=b)


False