In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
# arr[::-1]
np.flip(arr)    # 배열을 뒤집어줌

array([4, 3, 2, 1])

In [10]:
arr2d = np.arange(30).reshape(6,5)
arr2d
arr2d[::-1]

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [22]:
np.flip(arr2d)  #  = arr2d[::-1,::-1] 행과 열을 전부 다 뒤집음
# axis 에러가 나오는 경우가 있음. 이때는 축을 잘못 지정했을 떄
# np.flip(arr2d, axis=0) / axis(축) axes(모든 축)
# axis=0 은 열
# axis=1 은 행

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [49]:
np.sum(arr)
np.min(arr)
np.max(arr)
np.argmin(arr2d, axis=0) # 최소값의 '위치'를 알려줌
np.argmax(arr2d, axis=0) # 최소값의 '위치'를 알려줌


array([5, 5, 5, 5, 5], dtype=int64)

In [53]:
arr2d.mean()    # 해당 변수의 평균값
np.median(arr2d)    # 중위값을 확인(데이터 갯수가 짝수일 경우 중앙의 두 데이터의 평균)
                    # 1,2,3,4,10000 이런 식의 데이터라면 중위값을 이용하는 것이 좋다.(평균x)

14.5

In [79]:
np.all(2>1)
np.all([2>1, 5>3])
np.all([2>1, 5>3, 3<1]) # falss가 있으면 false를 반환, 아니면 true

True

In [61]:
np.any([1,2,3])
np.any([0,0,0]) # 하나라도 true면 true
np.any([0,1])

True

In [83]:
# 풀어오기
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

# np.all(a<=b, b<=c)  # 스칼라가 아니라 벡터라서 오류남
np.all([a<=b, b<=c])  # []로 한 줄로 만듦

True

In [84]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
arr.sum(axis=0) # 열 단위로 계산/ 2차원 이상이면 axis를 사용 가능

array([ 5,  7,  9, 11, 13])

In [87]:
arr.sum(axis=1) # 행 단위로 계산

array([10, 35])

In [89]:
arr.sum()

45

In [30]:
# max 값 구하기
a = np.array([[4, 3, 5, 7],
              [1, 12, 11, 9],
              [2, 15, 1, 14]])

np.max(a, axis=1)   # axis= 1 행의 최대값, =0 열의 최대값

array([ 7, 12, 15])

In [34]:
a.sort()    # 행 정렬 = a.sort(axis=0)
np.sort(a,axis=1)

a.sort(axis=0)  # 열 정렬
a

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [24]:
arr = np.array([40,10,20,90,50])
arr

array([40, 10, 20, 90, 50])

In [29]:
np.sort(arr)
np.sort(arr)[::-1]
np.flip(np.sort(arr))

array([90, 50, 40, 20, 10])

In [114]:
np.mean(arr)    # 평균 :주어진 수의 합을 주어진 데이터의 개수로 나눔
np.var(arr)     # 분산(모분산) : 편차의 제곱의 평균값(= 각 변수가 흩어진 정도)
#클수록 크게 흩뿌려진 상태, 작을수록 밀집 상태(= 비슷한 데이터)
np.std(arr)     # 표준편차 : 분산의 제곱근

27.85677655436824

In [115]:
np.var(arr)

776.0

In [118]:
np.sqrt(2)  # 제곱근 == np.var(arr) ** 0.5
np.sqrt(np.var(arr))  # 제곱근

27.85677655436824

In [121]:
np.var([1,2])
# mean = 1.5
# 1-mean => 1-1.5 => -0.5(분산값에는 마이너스를 계산하지 않음)
# 2-mean => 2-1.5 => 0.5

# 0.5**2(=0.25) + 0.5**2(=0.25) => 0.5
# 0.5/len([1,2]) = 0.25(분산값)

0.25

In [127]:
x = np.array([5,10,9,3,8])
np.percentile(x,0)
np.percentile(x,25)
np.percentile(x,50)
np.percentile(x,75)
np.percentile(x,100) # 퍼센테이지로 숫자 넣으면 됨

10.0

In [2]:
data = np.arange(11)
np.percentile(data,10)

1.0

In [5]:
np.random.seed(20) # 시드 : 세팅값
# 시드값을 지정해주면 그 다음 랜덤값은 고정이 됨

In [7]:
np.random.rand() # 0 <= 난수 <= 1

0.897713727909418

In [9]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
np.random.shuffle(x)
x

array([7, 5, 2, 9, 8, 0, 4, 3, 6, 1])

In [45]:
# choice
np.random.choice(x,3)

array([4, 1, 8])

In [89]:
np.random.randn() # 평균 0에 근접, 표준편차가 1에 가까운 데이터 추출
# np.mean(np.random.randn(10))
# np.std(np.random.randn(10))

1.5375527217507483

In [94]:
np.random.randint(2) # [0,2) 개구간 [이상, ( 미만

0

In [99]:
np.random.randint(2,4, size=(10,2))

array([[2, 2],
       [2, 3],
       [2, 2],
       [3, 2],
       [2, 2],
       [2, 3],
       [3, 3],
       [2, 2],
       [2, 2],
       [2, 2]])

In [120]:
data = np.random.randint(1,11, size=10)
data.sort()
data

array([2, 2, 2, 4, 4, 6, 6, 6, 7, 8])

In [108]:
np.unique(data)
np.unique(data, return_counts=True)
a, b = np.unique(data, return_counts=True)

In [110]:
a, b

(array([2, 3, 4, 6, 7]), array([2, 5, 1, 1, 1], dtype=int64))

In [121]:
# np.bincount(data, minlength=1)

array([0, 0, 3, 0, 2, 0, 3, 1, 1], dtype=int64)