In [9]:
import numpy as np

In [150]:
# 1. 
# 지금까지 
# - tile사용, tile 미사용,...공부한 명령어를 사용하여 다음과 같은 배열을 다양한 방법으로 만드시오.
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

# 최소 5가지 이상

a0 = np.zeros((1,3))
a1 = np.ones((1,2))
a2 = np.hstack([a0,a1])

asum = np.tile(a2,(3,1))

arr = np.arange(10,151,10).reshape(3,-1)

np.vstack([asum,arr]*2)

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [117]:
a0= [0,0,0,1,1]
a1= np.arange(10,151,10).reshape(3,-1)
np.vstack([[a0]*3,a1]*2,dtype=float)

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [118]:
a0= [0,0,0,1,1]
a1 = np.arange(10,51,10)
a2 = np.array([50,50,50,50,50])
np.vstack([[a0]*3,[a1],[a1+a2],[a1+a2*2]]*2,dtype=float)

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [133]:
a0 = np.zeros((1,3))
a1 = np.ones((1,2))
a2 = np.hstack([a0,a1]*3).reshape(3,-1)
a3 = np.arange(10,151,10).reshape(3,-1)
np.vstack([a2,a3]*2)

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [155]:
a0 = np.zeros((1,3))
a1 = np.ones((1,2))
a2 = np.hstack([a0,a1])
a3 = np.arange(10,151,10).reshape(3,-1)
b= a2.copy()
np.vstack([b,b,b,a3]*2)

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [55]:
# 2.  아래와 같은 구조의 배열을 생성하시오(2차원 배열로 만들어낼것)
# 1 2 3 4 5
# 10 9 8 7 6
# 11 12 13 14 15
# 20 19 18 17 16
# 21 22 23 24 25

arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

....................................

In [32]:
# 주어진 numpy 배열 arr의 모든 요소의 합계
import numpy as np

arr = np.array([1,2,3,4,5])

arr.sum()

15

In [33]:
# 두 개의 2D NumPy 배열 A와 B의 행렬 곱셈 구하기
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [43]:
# 두 개의 NumPy 배열 arr1과 arr2에서 요소별 최대값으로 이루어진 배열을 구하기

arr1 = np.array([1,3,5,7])
arr2 = np.array([2,4,6,8])

arr1.max(), arr2.max()

(7, 8)

In [52]:
# 주어진 2D NumPy 배열 arr의 행과 열을 교환(전치 행렬)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.transpose()
# arr.T.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# 주어진 NumPy 배열 arr에서 짝수만 선택하여 새로운 배열을 만들기(불리언 인덱싱)
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[(arr%2==0)]

array([ 2,  4,  6,  8, 10])