In [1]:
import numpy as np

In [22]:
# 1.
# 넘파이를 사용하여 다음과 같은 행렬을 만든다.
# 10 20 30 40
# 50 60 70 80

np.array([list(range(10,41,10)),list(range(50,81,10))])
np.array(list(range(10,81,10))).reshape(2,-1)
np.arange(10,81,10).reshape(2,-1)
np.linspace(10,80,8, dtype='i4') #??

array([10, 20, 30, 40, 50, 60, 70, 80])

In [24]:
# 2.
# 다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
# 이 행렬에서 값 7 을 인덱싱한다.
m[1][2]
# 이 행렬에서 값 14 을 인덱싱한다.
m[2][-1]
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[(m == 6) | (m == 7)]
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[(m == 7) | (m == 12)]
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:,[3,4]]
# ???

array([[3, 4],
       [8, 9]])

In [10]:
# 3. 값이 10에서 49를 원소로 가지고 있는 벡터 만들기
nums = np.array(list(range(10,50))).reshape(5,8)
nums = np.arange(10,50)
nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
# 4. 3번 배열의 원소를 뒤집어 출력
nums[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [12]:
# 1. 1차원 numpy 배열을 만들어 결과와 같이 출력하기
# [ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]
np.array(list(range(0,29,2)))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [13]:
# 2. 2차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[10, 20, 30, 40],
# 50, 60, 70, 80]]
np.array(list(range(10,81,10))).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [25]:
# 3. 3차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[[ 1, 2, 3],
# [ 4, 5, 6]],
# [[ 7, 8, 9],
# [10, 11, 12]],
# [[13, 14, 15],
# [16, 17, 18]],
# [[19, 20, 21],
# [22, 23, 24]]]

arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])
np.arange(1,25).reshape(4,2,3)
# x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [15]:
# 4. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
vector = np.array(range(0, 30, 2))

# 값 24 인덱싱
vector[vector == 24]
#  값 6 인덱싱
vector[vector == 6]

array([6])

In [16]:
# 5. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
matrix = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])

# - 값 8 인덱싱
matrix[matrix==8]
# - 값 2 인덱싱
matrix[matrix==2]
# - 값 9 인덱싱
matrix[matrix==9]
# - 값 15 인덱싱
matrix[matrix==15]

# 너무 풀이가 단조로움

array([15])

In [27]:
# 6. 아래와 같은 행렬을 작성해보세요
# [-1, -2, -3, -4, -5]
np.arange(-5,0)

array([-5, -4, -3, -2, -1])

In [31]:
# 7.
# 다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# 이 배열에서 3의 배수를 찾아라.
x[x % 3 == 0]
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x % 4 == 1]

# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x % 3 == 0) | (x % 4 == 1)]
# x

array([ 1,  3,  5,  6,  9, 12, 13, 15, 17, 18])

In [32]:
# 8. 다음 배열을 만들고 슬라이싱, 인덱싱 연습하세요
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

arr2d[1]

array([4, 5, 6])

In [33]:
import numpy as np

In [38]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
arr.ravel() # 평탄화
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
print(arr[np.newaxis].shape)
arr[np.newaxis]

(1, 3, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [48]:
for i in arr:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [49]:
a1 = np.ones((2,3))
a2 = np.zeros((2,2))
a3 = np.zeros((3,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
a2

array([[0., 0.],
       [0., 0.]])

In [52]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [53]:
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.vstack([a1, a3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.dstack([a3,a3])    # depth:깊이

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [58]:
np.stack([a2, a2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [63]:
a4 = np.arange(1,5).reshape(2,2)

In [69]:
np.dstack([a4,a4])

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]]])

In [72]:
np.stack([a4, a4])

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [73]:
a1= np.array([1,2,3])
a2= np.array([11,12,13])
# 위 배열들을 이용해서 array([1,2,3,11,12,13]) 만들기
np.r_[a1, a2] # 인덱서 함수 row

array([ 1,  2,  3, 11, 12, 13])

In [74]:
np.c_[a1, a2] # column

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [75]:
# tile : 동일한 배열을 연결
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [84]:
np.tile(arr, (3,2,2))

array([[[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]],

       [[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]],

       [[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]]])

In [ ]:
# [[0,0,0,1,1],
#  [0,0,0,1,1],
#  [0,0,0,1,1]] 이와 같은 결과 만들기
# 1. tile 2. stack류를 이용한 방법

In [85]:
x = np.arange(3)
y = np.arange(5)
x

array([0, 1, 2])

In [86]:
y

array([0, 1, 2, 3, 4])

In [87]:
a, b = np.meshgrid(x,y)

In [88]:
a

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [89]:
b

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [90]:
arr1 = np.arange(3)
arr2 = np.arange(10,13)

In [91]:
np.concatenate([arr1, arr2]) # np.hstack([arr1,arr2])

array([ 0,  1,  2, 10, 11, 12])

In [92]:
# array([[ 0,  1,  2,  3,  4,  5],
#        [10, 11, 12, 13, 14, 15],
#        [20, 21, 22, 23, 24, 25],
#        [30, 31, 32, 33, 34, 35],
#        [40, 41, 42, 43, 44, 45],
#        [50, 51, 52, 53, 54, 55]]) 이와 같이 만들어 볼 것

array([ 0,  1,  2, 10, 11, 12])

In [96]:
arr1 = np.arange(6)
arr2 = np.arange(0,51,10)
arr1 + arr2[:,np.newaxis] # 브로드캐스팅

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
# 벡터    스칼라
# 1    +   100     = 101
# 2                   102
# 3                   103
# ...                 ...
# 위와 같은 계산을 브로드캐스팅이라고 함

In [ ]:
# 행렬(2)    벡터(1)
# 0 1 2       10      10 11 12
# 1 2 3   +   11   =  12 13 14
# 2 3 4       12      14 15 16

In [98]:
# 벡터화 연산
a = np.arange(1,5)
b = np.array([4,2,2,4])
np.all(a>=b)

False

In [ ]:
# 1. 
# 지금까지 
# - tile사용, tile 미사용,...공부한 명령어를 사용하여 다음과 같은 배열을 다양한 방법으로 만드시오.
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

# 최소 5가지 이상

In [ ]:
# 2.  아래와 같은 구조의 배열을 생성하시오(2차원 배열로 만들어낼것)
# 1 2 3 4 5
# 10 9 8 7 6
# 11 12 13 14 15
# 20 19 18 17 16
# 21 22 23 24 25