In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [6]:
np.flip(arr) # arr[::-1] 이 코드와 동일함

array([4, 3, 2, 1])

In [7]:
arr2d = np.arange(30).reshape(6,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [8]:
arr2d[::-1]

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [14]:
np.flip(arr2d) # arr2d[::-1,::-1]
# axis 에러가 나오는 경우가 있음. 이때는 축을 잘못지정했을 때, 행, 열이 안맞는 경우
# axis(축) axes(모든 축)

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [20]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [26]:
np.sum(arr2d)
np.min(arr2d)
np.max(arr2d)
np.argmin(arr2d, axis=1) # 행의 최솟값 위치를 색출함
np.argmax(arr2d, axis=0) # 열의 최댓값 위치를 색출함

array([0, 0, 0, 0, 0, 0], dtype=int64)

In [31]:
arr2d.mean() # 해당 변수의 평균값
np.median(arr) # 중위값을 확인. 데이터가 짝수개일 경우, 중앙의 2개 값의 평균을 산출
# 1,2,3,4,10000 이런 식의 데이터라면 중위값을 이용하는 것이 좋음(평균x)

2.5

In [34]:
np.all(2>1)
np.all([2>1, 5>3])
np.all([2>1, 5>3, 3<1]) # false가 있으면 false를 반환, 아니면 True

False

In [37]:
np.any([1,2,3])
np.any([0,0,0]) # 전부 false이므로 false를 반환
np.any([0,1])

True

In [39]:
# 풀어보기
# a에 저장된 값들이 모두 b에 저장된 값보다 작거나 같으면서
# b에 저장된 값들이 모두 c에 저장된 값보다 작거나 같은가?
# True가 나와야 함
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [ ]:
# 스칼라, 벡터
# 스칼라? = 하나의 직선(1차원)
# 벡터? = 두개이상의 직선(2차원)

In [48]:
np.all([a<=b , b<=c])

True

In [49]:
arr = np.arange(10).reshape(2,5)

In [50]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
arr.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [52]:
arr.sum(axis=1)

array([10, 35])

In [53]:
arr.sum()

45

In [57]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
# a 배열의 각 행 최댓값을 구하라

In [58]:
a.sort()
a


array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [61]:
a.sort(axis=0)
a

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [62]:
np.sort(a, axis=1)

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [64]:
arr= np.array([40,10,20,90,50])
arr

array([40, 10, 20, 90, 50])

In [67]:
np.sort(arr)
np.sort(arr)[::-1]
np.flip(np.sort(arr))

array([90, 50, 40, 20, 10])

In [68]:
arr

array([40, 10, 20, 90, 50])

In [71]:
np.mean(arr) # 평균: 주어진 수의 합을 주어진 데이터의 개수로 나눔
np.var(arr) # 분산(모분산): 편차의 제곱의 평균값(=각 변수가 흩어진 정도)
# 클수록 크게 흩뿌려진 상태, 작을수록 밀집 상태(=비슷한 데이터)
np.std(arr) # 표준편차 : 분산의 제곱근

27.85677655436824

In [74]:
np.sqrt(2) # 제곱근 == np.var(arr) ** 0.5
np.var(arr)

27.85677655436824

In [76]:
np.var([1,2])
# mean = 1.5
# 1-mean => 1-1.5 => 0.5(분산값은 마이너스를 계산하지 않음)
# 2-mean => 2-1.5 => 0.5
# 0.5**2(=0.25)    +    0.5 ** 2(0.25) => 0.5
# 0.5/(len([1,2]) = 0.25(분산값)

0.25

In [78]:
x= np.array([5,10,9,3,8])

In [85]:
np.percentile(x,0)
np.percentile(x,25)
np.percentile(x,50)
np.percentile(x,75)
np.percentile(x,100)

10.0

In [91]:
data = np.arange(12)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
np.percentile(data,20)
np.percentile(data,50)

5.5

In [ ]:
# 1.
# 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

# 전체의 최댓값
# 각 행의 합
# 각 행의 최댓값
# 각 열의 평균
# 각 열의 최솟값

import numpy as np
data = np.arange(30).reshape(5,6)
data

In [ ]:
# 2.
# 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 
# 영어 성적을 기준으로 각 열(column)을 재정렬하라.

# array([[  1,    2,    3,    4],
#        [ 46,   99,  100,   71],
#        [ 81,   59,   90,  100]])


np.array([[  1,    2,    3,    4],
        [ 46,   99,  100,   71],
        [ 81,   59,   90,  100]])