In [1]:
# 파이썬 => 리스트
def test():
    return 1
lst = [1,2,'3', [1], test(),...]

In [2]:
lst

[1, 2, '3', [1], 1, Ellipsis]

In [ ]:
import numpy # numpy는 속도가 빠름, 메모리 할당이 적음, 자료형이 같은 동일한 것만 저장됨
# 벡터연산을 위해 자주 쓰임
# 행벡터, 열벡터(행렬)
# 행벡터 => x = [x1, x2, x3, ... xn]
# 열벡터 => y = 
# [ [y1],
#  [y2],
#  [y3],
#  ..
# [yn]]

In [3]:
import numpy as np

In [4]:
x = [1,2,3]
arr = np.array(x)

In [6]:
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [10]:
import time

data = list(range(1,100000000))
ans = []

In [11]:
start = time.time()
for i in data:
    ans.append(i*2)
end = time.time()
print(end-start)

10.681716442108154


In [12]:
arr_data = np.array(data)
arr_data

array([       1,        2,        3, ..., 99999997, 99999998, 99999999])

In [13]:
start = time.time()
ans2 = arr_data * 2 
end = time.time()
print(end-start)

0.14868426322937012


In [14]:
ans2

array([        2,         4,         6, ..., 199999994, 199999996,
       199999998])

In [15]:
x = [1,2]
y = [3,4]
x + y

[1, 2, 3, 4]

In [16]:
np.array(x) + np.array(y)

array([4, 6])

In [18]:
np.array(x) + 1

array([2, 3])

In [19]:
np.array([1,2,3]) + np.array([0,1,0])

array([1, 3, 3])

In [21]:
lst = list(range(1,101))

In [22]:
arr = np.array(lst)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [57]:
arr[(arr >= 50) & (arr<70)] # boolean 참조
# true가 되는 값에 대해서 출력

array([], dtype=int32)

In [30]:
np.array([1,2,3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [33]:
# 2차원 배열 만들기

arr = np.array([[1,2,3],[4,5,6]])
arr.ndim # 몇차원인지 알려줌
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [38]:
np.array([list(range(1,4)), list(range(4,7))])

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.array([list(range(1,4)), list(range(4,7))]).reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [54]:
arr[1][2]
arr[1, -1]

6

In [63]:
arr.astype('str')

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

In [ ]:
# numpy 어려운 영역임. 대기업에서도 이틀동안 배열만 다룸
# 데이터 사이언스 직군에는 넘파이를 사용해야됨(인공지능 분야 포함)

In [6]:
import numpy as np
kakao = np.loadtxt('kakao_pre.csv', skiprows=1, delimiter=',', dtype=np.float32)
kakao

array([[  58000.   ,   58900.   ,   57800.   ,   58300.   ,   58237.387,
        1047114.   ],
       [  57200.   ,   57500.   ,   56000.   ,   57200.   ,   57138.57 ,
        2288474.   ],
       [  57500.   ,   58200.   ,   57100.   ,   57700.   ,   57638.03 ,
        1821528.   ],
       ...,
       [  48350.   ,   48850.   ,   48300.   ,   48600.   ,   48600.   ,
        1015126.   ],
       [  48150.   ,   48550.   ,   48050.   ,   48300.   ,   48300.   ,
         889047.   ],
       [  49000.   ,   50300.   ,   49000.   ,   49150.   ,   49150.   ,
        1099015.   ]], dtype=float32)

In [7]:
kakao.shape

(246, 6)

In [16]:
# 값이 5에서 30을 원소로 가지는 2행 벡터 생성
np.array(list(range(5,31))).reshape(2,-1)

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [18]:
arr = np.array(['apple', 'bananaaaaaaaaaa', 'peach'])
arr.dtype

dtype('<U15')

In [26]:
np.array([1,2,3], dtype='i2')
# mac os는 64비트를 기준으로 함

array([1, 2, 3], dtype=int16)

In [32]:
arr1 = np.array(list(range(10,14)))
arr2 = np.array(list(range(10,14)))
arr3 = np.array(list(range(2,4)))
arr1, arr2, arr3

(array([10, 11, 12, 13]), array([10, 11, 12, 13]), array([2, 3]))

In [41]:
arr1 + 10 # 요소간 연산 => 연산할 데이터가 길이가 1일 경우 동일한 크기의 배열로 변환하여 연산을 진행
arr1 * 2 # 행렬 곱셈
# arr1 - arr3 이건 계산 못함
arr1.reshape(2,2) - arr3 # 해당하는 행과 열에 대해서만 계산을 함
arr1.reshape(2,2) * arr2.reshape(2,2) # 요소간 곱셈

array([[100, 121],
       [144, 169]])

In [44]:
~(arr1 == arr2) # not 연산자
arr1 != arr2

array([False, False, False, False])

In [48]:
# 1~24까지의 값 2*3*4 행렬 생성
# np.array(range(1,25)).reshape(2,3,4)
np.arange(1,25, 2).reshape(2,-1)

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23]])

In [51]:
# boolean 참조
arr = np.arange(1,5)
idx = np.array([True, True, False, False])
arr[idx]

array([1, 2])

In [53]:
np.min(arr)
np.max(arr)

4

In [55]:
arr[(arr == np.min(arr)) | (arr == np.max(arr))]

array([1, 4])

In [58]:
lst = list(range(1,10))
for i in lst:
    if(i == 5):
        print(i)

arr[arr == 4]

5


array([4])

In [ ]:
# 11부터 20까지의 수가 저장된 배열을 생성

In [60]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [62]:
arr[np.array([1,3])]

array([12, 14])

In [63]:
idx = np.array([0,0,0,1,1,1,1,2,3,4])
arr[idx]

array([11, 11, 11, 12, 12, 12, 12, 13, 14, 15])

In [67]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [71]:
arr[:,[3,2,1]]

array([[ 4,  3,  2],
       [ 9,  8,  7],
       [14, 13, 12],
       [19, 18, 17],
       [24, 23, 22]])

In [74]:
# 무한대(inf): np.inf
# np.array([1])/np.array([0])
np.log(0)

C:\Users\fkfma\AppData\Local\Temp\ipykernel_6276\2403776038.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [83]:
# np.array()
# np.arange()
np.zeros((4,4))
np.ones((4,4)) * 255

array([[255., 255., 255., 255.],
       [255., 255., 255., 255.],
       [255., 255., 255., 255.],
       [255., 255., 255., 255.]])

In [86]:
# np.linspace(시작할 숫자, 마지막 숫자, 총 데이터 개수)
np.linspace(0, 10, 5) # 보간법(interpolate) linear regression랑 비슷함

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [91]:
arr2 = arr[:,[1,2,3]]
arr2

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [95]:
arr2.T

array([[ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [100]:
# 사과, 딸기, 바나나
data = np.array([[1,5,2],
                 [4,3,2],
                 [1,2,3]])
price = np.array([[1000],[3000],[5000]])
data.shape
price.shape
# data배열과 price배열간 행렬의 곱셈 연산
print(data.dot(price)) # 벡터의 내적
print(data@price)
# cnn할 때 보게될 코드(이미지 처리)

[[26000]
 [23000]
 [22000]]
[[26000]
 [23000]
 [22000]]


In [115]:
a = np.array([1,2,3])
b = a # soft copy

In [116]:
b[1] = 99

In [117]:
b

array([ 1, 99,  3])

In [118]:
a

array([ 1, 99,  3])

In [119]:
# soft copy
# a = b 데이터공유

# deep copy
a = np.array([1,2,3])
b = a.copy()

In [120]:
b[1] = 99

In [121]:
b, a

(array([ 1, 99,  3]), array([1, 2, 3]))

In [122]:
np.random.random() # random도 있음

0.772248907146437